# Generated by Django 4.2.5 on 2023-09-28 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('dni', models.PositiveBigIntegerField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_vehicular', models.CharField(max_length=7)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=30)),
                ('n_serie', models.CharField(max_length=18)),
                ('n_motor', models.CharField(max_length=18)),
                ('n_vin', models.CharField(max_length=18)),
                ('color', models.CharField(max_length=30)),
                ('placa_vigente', models.CharField(max_length=7)),
                ('placa_anterior', models.CharField(max_length=7)),
                ('estado', models.CharField(max_length=15)),
                ('anotaciones', models.CharField(max_length=20)),
                ('sede', models.CharField(max_length=20)),
                ('propietarios', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('estado_civil', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
            bases=('api.usuario',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Policia',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rango', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
            bases=('api.usuario',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehiculo')),
                ('policia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.policia')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_de_deteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(max_length=30)),
                ('placa_detectada', models.CharField(max_length=7)),
                ('resultado_deteccion', models.TextField()),
                ('confianza_deteccion', models.CharField(max_length=15)),
                ('imagen_capturada', models.ImageField(upload_to='imagenes/registros/')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehiculo')),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ciudadano')),
                ('policia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.policia')),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehiculo')),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ciudadano')),
            ],
        ),
    ]
